version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.13.1
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Verify installed packages
          command: |
            source .venv/bin/activate
            pip freeze 
      - run:
          name: Run tests
          command: |
            source .venv/bin/activate
            pytest  

workflows:
  version: 2
  build:
    jobs:
      - build
